# Generated by Django 3.2.13 on 2023-02-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAsistencias',
            fields=[
                ('idasist', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('permisos', models.CharField(max_length=1)),
                ('idest4lista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Estudiantes.estudiante')),
            ],
        ),
    ]
