# Generated by Django 3.2.13 on 2023-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0004_alter_listaasistencias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaasistencias',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
