# Generated by Django 3.2.13 on 2023-02-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0005_alter_listaasistencias_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaasistencias',
            name='fecha',
        ),
    ]
