# Generated by Django 3.2.13 on 2023-02-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Estudiantes', '0007_listaasistencias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='idcur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cursos.curso'),
        ),
    ]
