# Generated by Django 3.2.13 on 2023-02-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Estudiantes', '0008_alter_estudiante_idcur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='idcur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso'),
        ),
        migrations.AlterField(
            model_name='listaasistencias',
            name='idest4lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante'),
        ),
    ]
