# Generated by Django 3.2.13 on 2023-03-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0009_auto_20230226_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idact', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAct', models.CharField(max_length=25)),
                ('fechaAct', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('idnota', models.AutoField(primary_key=True, serialize=False)),
                ('valorNota', models.IntegerField()),
                ('fechaNota', models.DateTimeField()),
                ('idAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.actividades')),
            ],
        ),
    ]
