# Generated by Django 3.2.13 on 2023-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0010_actividades_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaasistencias',
            old_name='fecha',
            new_name='fechaAsist',
        ),
        migrations.RenameField(
            model_name='listaasistencias',
            old_name='idasist',
            new_name='idAsist',
        ),
        migrations.RenameField(
            model_name='listaasistencias',
            old_name='idest4lista',
            new_name='idestLista',
        ),
        migrations.RemoveField(
            model_name='listaasistencias',
            name='permisos',
        ),
        migrations.AddField(
            model_name='listaasistencias',
            name='valorAsist',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
