# Generated by Django 3.2.13 on 2023-03-04 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0011_auto_20230304_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='fechaNota',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
