# Generated by Django 3.2.13 on 2023-03-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0012_alter_notas_fechanota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaasistencias',
            old_name='idestLista',
            new_name='idestAsist',
        ),
    ]
