# Generated by Django 3.2.13 on 2023-03-05 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0013_rename_idestlista_listaasistencias_idestasist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 15, 42, 24, 830012), editable=False),
        ),
    ]
