# Generated by Django 3.2.13 on 2023-03-05 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0017_alter_listaasistencias_fechaasist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
