# Generated by Django 3.2.13 on 2023-03-09 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0019_alter_listaasistencias_fechaasist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.date(2023, 3, 9)),
        ),
        migrations.AlterField(
            model_name='listaasistencias',
            name='valorAsist',
            field=models.FloatField(default=0),
        ),
    ]
