# Generated by Django 3.2.13 on 2023-03-10 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0020_auto_20230309_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='consigna',
            field=models.TextField(default='no instruida'),
        ),
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
    ]
