# Generated by Django 4.1.6 on 2023-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0020_alter_listaasistencias_fechaasist'),
        ('Estudiantes', '0020_auto_20230309_1336'),
    ]

    operations = [
    ]
