# Generated by Django 3.2.13 on 2023-03-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0021_auto_20230310_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='consigna',
        ),
        migrations.AddField(
            model_name='actividades',
            name='consignaAct',
            field=models.TextField(default='no instruida'),
        ),
    ]
