# Generated by Django 3.2.13 on 2023-03-11 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0022_auto_20230310_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='idAct',
        ),
        migrations.AddField(
            model_name='notas',
            name='idActNota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.actividades'),
        ),
        migrations.AddField(
            model_name='notas',
            name='idestNota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.date(2023, 3, 11)),
        ),
    ]
