# Generated by Django 4.1.6 on 2023-03-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0022_alter_listaasistencias_fechaasist'),
        ('Estudiantes', '0023_auto_20230311_1737'),
    ]

    operations = [
    ]
