# Generated by Django 3.2.13 on 2023-03-18 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Estudiantes', '0023_auto_20230311_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaasistencias',
            name='ideCurAsist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso'),
        ),
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
        migrations.AlterField(
            model_name='notas',
            name='idestNota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante'),
        ),
    ]
