# Generated by Django 4.1.6 on 2023-03-12 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0024_merge_20230312_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaasistencias',
            name='fechaAsist',
            field=models.DateField(default=datetime.date(2023, 3, 12)),
        ),
        migrations.AlterField(
            model_name='notas',
            name='idestNota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante'),
        ),
    ]
