# Generated by Django 4.1.6 on 2023-03-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0024_auto_20230318_1016'),
        ('Estudiantes', '0025_alter_listaasistencias_fechaasist_and_more'),
    ]

    operations = [
    ]
